### ISSUE TITLE
Could not pass event PlayerInteractEvent to BuildSystem v2.21.2

### ISSUE THREAD

**Issue by avalonworldw** [Trichtern/BuildSystem#149]
### Steps to reproduce

Without any operation, the background will refresh

### What is expected?

This problem may not occur on the spigot, because mohist is a confused version, but it supports the spigot plug-in, so I want to know the cause of the problem,
If possible, please fix it,

And the worldborder does not display normally on my server

### What is actually happening?

I guess it may be an interactive error

### Server Info
Server Core Version：mohist-1.12.2-321-server.jar
BuildSystem-2.21.2.jar

```shell
[20:13:39 ERROR]: Could not pass event PlayerInteractEvent to BuildSystem v2.21.2
 org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:63) ~[EventExecutor.class:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:331) ~[CraftEventFactory.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:501) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:1151) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(CPacketPlayerTryUseItemOnBlock.java:61) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(CPacketPlayerTryUseItemOnBlock.java:13) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_331]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_331]
        at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:840) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:778) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_331]
Caused by: java.lang.IllegalArgumentException: Unsupported material with no data value: ENDERIO_ITEM_STELLAR_ALLOY_SWORD
        at com.eintosti.buildsystem.util.external.xseries.XMaterial.lambda$matchXMaterial$0(XMaterial.java:1691) ~[?:?]
        at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_331]
        at com.eintosti.buildsystem.util.external.xseries.XMaterial.matchXMaterial(XMaterial.java:1691) ~[?:?]
        at com.eintosti.buildsystem.listener.SettingsInteractListener.managePlacePlantsSetting(SettingsInteractListener.java:141) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor99.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:?]
        ... 17 more
```

**Comment by Trichtern** [comment]
By looking at the logs it looks like the worlds custom item is set to a non-vanilla item. Therefore it can't be found by the arterial which allows for backwards compatibility. 

Try changing the item to a vanilla one and see if the error persists

**Comment by avalonworldw** [comment]
> 通过查看日志，看起来世界的自定义项目被设置为非原版项目。因此，它无法被允许向后兼容的动脉找到。
> 
> 尝试将项目更改为原版项目，看看错误是否仍然存在

It is the default, just a clock

  builder:
    block-worldedit-non-builder: true
    world-edit-wand: WOODEN_AXE
    creator-is-builder: false
  navigator:
    item: CLOCK
    give-item-on-join: true

**Comment by Trichtern** [comment]
Are you using any non-vanilla items in interact with your world?

**Comment by avalonworldw** [comment]
No, I didn't do anything

**Comment by avalonworldw** [comment]
No, I didn't do anything
